name: Example Action

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run main
        id: main
        uses: ./ # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
